# Generated by Django 6.0.3 on 2026-03-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_demande', models.CharField(choices=[('MISE_EN_LIGNE', 'Mise en ligne'), ('MODIFICATION', 'Modification'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TRAITEE', 'Traitée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('reponse_admin', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Demande de contact',
                'verbose_name_plural': 'Demandes de contact',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Quittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='quittances/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('envoyee', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Quittance',
                'verbose_name_plural': 'Quittances',
                'ordering': ['-date_generation'],
            },
        ),
    ]
