# Generated by Django 6.0.3 on 2026-03-26 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0002_initial'),
        ('notifications', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecontact',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='utilisateurs.proprietaire'),
        ),
        migrations.AddField(
            model_name='quittance',
            name='paiement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quittance', to='comptabilite.paiement'),
        ),
    ]
