# Generated by Django 6.0.3 on 2026-03-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('MISE_EN_LIGNE', 'Mise en ligne')], max_length=50)),
                ('modele', models.CharField(max_length=100)),
                ('objet_id', models.IntegerField(blank=True, null=True)),
                ('ancienne_valeur', models.TextField(blank=True)),
                ('nouvelle_valeur', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('modele_3d', models.FileField(blank=True, null=True, upload_to='modeles_3d/')),
                ('equipements', models.JSONField(blank=True, default=list)),
                ('loyer_hc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taux_commission', models.FloatField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('statut', models.CharField(choices=[('LOUE', 'Loué'), ('VACANT', 'Vacant'), ('EN_TRAVAUX', 'En travaux'), ('EN_VENTE', 'En vente'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('REJETE', 'Rejeté')], default='VACANT', max_length=25)),
                ('en_ligne', models.BooleanField(default=False)),
                ('motif_rejet', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('bail_actif', models.BooleanField(default=False)),
                ('visite_en_cours', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Biens',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='PhotoBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos_biens/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='TypeBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de bien',
                'verbose_name_plural': 'Types de bien',
            },
        ),
    ]
