# Generated by Django 6.0.3 on 2026-03-26 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patrimoine', '0001_initial'),
        ('utilisateurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bien',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biens', to='utilisateurs.proprietaire'),
        ),
        migrations.AddField(
            model_name='bien',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biens', to='patrimoine.categorie'),
        ),
        migrations.AddField(
            model_name='photobien',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_bien', to='patrimoine.bien'),
        ),
        migrations.AddField(
            model_name='bien',
            name='photos_upload',
            field=models.ManyToManyField(blank=True, related_name='biens', to='patrimoine.photobien'),
        ),
        migrations.AddField(
            model_name='typebien',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='patrimoine.categorie'),
        ),
        migrations.AddField(
            model_name='bien',
            name='type_bien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens', to='patrimoine.typebien'),
        ),
        migrations.AlterUniqueTogether(
            name='typebien',
            unique_together={('categorie', 'nom')},
        ),
    ]
