# Generated by Django 6.0.3 on 2026-03-14 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patrimoine', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biens', to='utilisateurs.proprietaire'),
        ),
        migrations.AddField(
            model_name='bien',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biens', to='patrimoine.categorie'),
        ),
        migrations.AddField(
            model_name='typebien',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='patrimoine.categorie'),
        ),
        migrations.AddField(
            model_name='bien',
            name='type_bien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens', to='patrimoine.typebien'),
        ),
        migrations.AlterUniqueTogether(
            name='typebien',
            unique_together={('categorie', 'nom')},
        ),
    ]
