# Generated by Django 6.0.3 on 2026-03-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_depense', models.CharField(choices=[('TRAVAUX', 'Travaux'), ('TAXES', 'Taxes'), ('FRAIS_AGENCE', "Frais d'agence"), ('COPROPRIETE', 'Copropriété'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_depense', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('facture', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paiement', models.DateField()),
                ('methode', models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement'), ('FEDAPAY', 'FedaPay'), ('CHEQUE', 'Chèque')], default='ESPECES', max_length=20)),
                ('reference_fedapay', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
