# Generated by Django 6.0.3 on 2026-03-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('loyer_initial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('depot_garantie', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taux_revision', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bail',
                'verbose_name_plural': 'Baux',
                'ordering': ['-date_entree'],
            },
        ),
        migrations.CreateModel(
            name='BienSauvegarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bien sauvegardé',
                'verbose_name_plural': 'Biens sauvegardés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('piece_identite', models.FileField(blank=True, null=True, upload_to='pieces_identite/')),
                ('garant_nom', models.CharField(blank=True, max_length=100)),
                ('garant_prenom', models.CharField(blank=True, max_length=100)),
                ('garant_telephone', models.CharField(blank=True, max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Locataire',
                'verbose_name_plural': 'Locataires',
            },
        ),
        migrations.CreateModel(
            name='Visitebien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateTimeField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('ANNULEE', 'Annulée'), ('EFFECTUEE', 'Effectuée')], default='EN_ATTENTE', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
                'ordering': ['-date_visite'],
            },
        ),
    ]
