# Generated by Django 6.0.3 on 2026-03-26 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locataires', '0001_initial'),
        ('patrimoine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bail',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baux', to='patrimoine.bien'),
        ),
        migrations.AddField(
            model_name='biensauvegarde',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sauvegardes', to='patrimoine.bien'),
        ),
    ]
