# Generated by Django 6.0.3 on 2026-03-26 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locataires', '0002_initial'),
        ('patrimoine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='biensauvegarde',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biens_sauvegardes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locataire',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_locataire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bail',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baux', to='locataires.locataire'),
        ),
        migrations.AddField(
            model_name='visitebien',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='patrimoine.bien'),
        ),
        migrations.AddField(
            model_name='visitebien',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='biensauvegarde',
            unique_together={('bien', 'client')},
        ),
    ]
